enum ActionType {
  AUTH_USER_SUCCESS = "AUTH_USER_SUCCESS",
  AUTH_USER_FAILURE = "AUTH_USER_FAILURE",
  AUTH_PRIVATE_LOADING = "AUTH_PRIVATE_LOADING",
  AUTH_USER_LOGOUT = "AUTH_USER_LOGOUT",
}

export default ActionType;
